spring:
  application:
    name: hive-ai-code-mother
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hive.hiveaicodemother.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn